<div class="row align-items-center mt-2 ml-5">
	<ol>
		<li>
			<h3> Acknowledgment </h3>
			<p> You the Administrator of this server acknowledge and understand that Truth or Dare Online is an adult
				game with adult content not intended for anybody under 18.</p>
		</li>
		<li>
			<h3>Precautions for Under 18s</h3>
			<p>You agree that you will take every reasonable precaution to prevent children under the age of 18 from
				viewing any channels this bot is used in.</p>
		</li>
		<li>
			<h3>Reporting</h3>
			<p>You understand that any user can report your server for allowing under 18's to use or view content
				generated by this bot or its users.</p>
		</li>
		<li>
			<h3>Investigation</h3>
			<p>You agree that if such a report is submitted, a member of the bot's moderation team may investigate your
				server.</p>
		</li>
		<li>
			<h3>Consequences</h3>
			<p>You understand that your server could be banned from using the bot and reported for breaching Discord's
				ToS
				if a member of the moderation team finds you to be breaching these terms, Discord ToS, or the law.</p>
		</li>
		<li>
			<h3>Data</h3>
			<p>You agree to allow the bot to store some basic information about the community for moderation purposes:
				Your
				community ID number, and your community's name.</p>
		</li>
	</ol>
</div>